//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMieter.WebUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eMieter.WebUI.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Konto wurde erfolgreich erstellt..
        /// </summary>
        public static string AccountCreateSuccessfully {
            get {
                return ResourceManager.GetString("AccountCreateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktion.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haus hinzufügen/bearbeiten.
        /// </summary>
        public static string Add_Edit_House {
            get {
                return ResourceManager.GetString("Add/Edit House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mietobjekt hinzufügen/bearbeiten.
        /// </summary>
        public static string Add_Edit_Rental_Property {
            get {
                return ResourceManager.GetString("Add/Edit Rental Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer hinzufügen/bearbeiten.
        /// </summary>
        public static string Add_Edit_User {
            get {
                return ResourceManager.GetString("Add/Edit User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mietverhältnis hinzufügen/bearbeiten.
        /// </summary>
        public static string Add_EditTenancy {
            get {
                return ResourceManager.GetString("Add/EditTenancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mieter hinzufügen/bearbeiten.
        /// </summary>
        public static string Add_EditTenant {
            get {
                return ResourceManager.GetString("Add/EditTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haus hinzufügen.
        /// </summary>
        public static string Add_House {
            get {
                return ResourceManager.GetString("Add House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mietobjekt hinzufügen.
        /// </summary>
        public static string Add_Rental_Property {
            get {
                return ResourceManager.GetString("Add Rental Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzer hinzufügen.
        /// </summary>
        public static string Add_User {
            get {
                return ResourceManager.GetString("Add User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mietvertrag hinzufügen.
        /// </summary>
        public static string AddTenancy {
            get {
                return ResourceManager.GetString("AddTenancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mieter hinzufügen.
        /// </summary>
        public static string AddTenant {
            get {
                return ResourceManager.GetString("AddTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte alle notwendigen Felder ausfüllen..
        /// </summary>
        public static string AllRequiredFields {
            get {
                return ResourceManager.GetString("AllRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bereits registriert?.
        /// </summary>
        public static string AlreadyRegistered {
            get {
                return ResourceManager.GetString("AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bist du dir sicher?.
        /// </summary>
        public static string Are_you_sure_ {
            get {
                return ResourceManager.GetString("Are you sure?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Rücken.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache ändern.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stadt.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nah dran.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellungsdatum.
        /// </summary>
        public static string Created_Date {
            get {
                return ResourceManager.GetString("Created Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuen Account erstellen?.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geburtsdatum.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail ist bereits im System vorhanden..
        /// </summary>
        public static string EmailExist {
            get {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email oder Passwort ist falsch..
        /// </summary>
        public static string EmailPasswordIncorrect {
            get {
                return ResourceManager.GetString("EmailPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Enddatum der Miete sollte nach dem Startdatum der Miete liegen..
        /// </summary>
        public static string EndDateGreaterThan {
            get {
                return ResourceManager.GetString("EndDateGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EWID.
        /// </summary>
        public static string EWID {
            get {
                return ResourceManager.GetString("EWID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte füllen Sie Ihre E-Mail aus.
        /// </summary>
        public static string FillEmail {
            get {
                return ResourceManager.GetString("FillEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie Ihr Passwort ein.
        /// </summary>
        public static string FillPassword {
            get {
                return ResourceManager.GetString("FillPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boden.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wohnfläche Quadratmeter.
        /// </summary>
        public static string Living_Area_Square_Meters {
            get {
                return ResourceManager.GetString("Living Area Square Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ort.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldung.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausloggen.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haus verwalten.
        /// </summary>
        public static string Manage_House {
            get {
                return ResourceManager.GetString("Manage House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mietobjekte verwalten.
        /// </summary>
        public static string Manage_Rental_Property {
            get {
                return ResourceManager.GetString("Manage Rental Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer verwalten.
        /// </summary>
        public static string Manage_Users {
            get {
                return ResourceManager.GetString("Manage Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hausdetails verwalten.
        /// </summary>
        public static string ManageHouseDetail {
            get {
                return ResourceManager.GetString("ManageHouseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mietobjektdetails verwalten.
        /// </summary>
        public static string ManageRentalPropertyDetail {
            get {
                return ResourceManager.GetString("ManageRentalPropertyDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mietvertrag verwalten.
        /// </summary>
        public static string ManageTenancy {
            get {
                return ResourceManager.GetString("ManageTenancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mietvertragsdetails verwalten.
        /// </summary>
        public static string ManageTenancyDetail {
            get {
                return ResourceManager.GetString("ManageTenancyDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mieter verwalten.
        /// </summary>
        public static string ManageTenant {
            get {
                return ResourceManager.GetString("ManageTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postleitzahl.
        /// </summary>
        public static string PostCode {
            get {
                return ResourceManager.GetString("PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mietgegenstand.
        /// </summary>
        public static string Rental_Property {
            get {
                return ResourceManager.GetString("Rental Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mietnebenkosten Akonto.
        /// </summary>
        public static string RentalAdditionalCostsAkonto {
            get {
                return ResourceManager.GetString("RentalAdditionalCostsAkonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mietkosten netto monatlich.
        /// </summary>
        public static string RentalCostNetMonthly {
            get {
                return ResourceManager.GetString("RentalCostNetMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enddatum der Miete.
        /// </summary>
        public static string RentalEndDate {
            get {
                return ResourceManager.GetString("RentalEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startdatum der Miete.
        /// </summary>
        public static string RentalStartDate {
            get {
                return ResourceManager.GetString("RentalStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zimmeranzahl.
        /// </summary>
        public static string Room_Count {
            get {
                return ResourceManager.GetString("Room Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bleibe eingeloggt.
        /// </summary>
        public static string StayLogin {
            get {
                return ResourceManager.GetString("StayLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straße.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfolg.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Mietverhältnis ist in diesem Zeitraum bereits aktiv..
        /// </summary>
        public static string TenancyisActive {
            get {
                return ResourceManager.GetString("TenancyisActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mieterin.
        /// </summary>
        public static string Tenant {
            get {
                return ResourceManager.GetString("Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie möchten diesen Datensatz löschen!.
        /// </summary>
        public static string you_want_to_delete_this_record_ {
            get {
                return ResourceManager.GetString("you want to delete this record!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre wurde erfolgreich gespeichert..
        /// </summary>
        public static string Your_has_been_saved_successfully_ {
            get {
                return ResourceManager.GetString("Your has been saved successfully.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Datensatz wurde gelöscht..
        /// </summary>
        public static string Your_record_has_been_deleted_ {
            get {
                return ResourceManager.GetString("Your record has been deleted.", resourceCulture);
            }
        }
    }
}
